version: '3'

services:
    web:
        image: nginx:alpine
        ports:
          - "9080:80"
        volumes:
            - ~/dev/trinity-manager:/var/www/trinity-manager
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/trinity-manager.conf:/etc/nginx/conf.d/default.conf
    php:
        build:
          context: ./php-fpm
        image: trinity-php:alpine
        volumes:
            - ~/dev/trinity-manager:/var/www/trinity-manager
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    mysql:
        image: mysql:latest
        ports:
          - "8086:3306"
        environment:
          MYSQL_USER: "trinity"
          MYSQL_PASSWORD: "trinity"
        volumes:
          - ./mysql/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    cache:
        image: redis:alpine
    world:
        image: wizofgoz/trinity-world:latest
        ports:
          - "8085:8085"
        volumes:
            - ./server/etc/worldserver.conf:/srv/server/etc/worldserver.conf
        depends_on:
          - mysql
        command: /home/server/bin/worldserver
    auth:
        image: wizofgoz/trinity-auth:latest
        ports:
          - "3724:3724"
        volumes:
            - ./server/etc/authserver.conf:/srv/server/etc/authserver.conf
        depends_on:
          - mysql
        command: /home/server/bin/authserver
    echo-server:
        image: lagun4ik/laravel-echo-server
        ports:
          - "1194:1194/udp"
        restart: always
        volumes:
          - ./echo-server/data/:/app

