version: '2'

services:
    trinity-manager-web:
        image: nginx:latest
        ports:
          - "8080:80"
        volumes:
            - ~/dev/trinity-manager:/var/www/trinity-manager
#            - ./nginx:/etc/nginx
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/sites-available/trinity-manager.conf:/etc/nginx/conf.d/default.conf
        networks:
          trinity-network:
            ipv4_address: 10.6.0.5
    trinity-manager-php:
        image: library/php
#        command: bash -c "cd /var/www/trinity-manager; npm run docker;"
        volumes:
            - ~/dev/trinity-manager:/var/www/trinity-manager
            - ./php-fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        networks:
          trinity-network:
            ipv4_address: 10.6.0.6
    trinity-manager-mariadb:
        image: mariadb
        ports:
          - "8081:3306"
        environment:
          - "MYSQL_ROOT_PASSWORD=trinity"
        networks:
          trinity-network:
            ipv4_address: 10.6.0.7
    trinity-manager-memcached:
        image: memcached
        command: memcached -m 64m
        networks:
          trinity-network:
            ipv4_address: 10.6.0.8
    trinity-manager-servers:
        image: nicolaw/trinitycore
        networks:
          trinity-network:
            ipv4_address: 10.6.0.9
networks:
    trinity-network:
        driver: bridge
        ipam:
          config:
            - subnet: 10.6.0.0/16
              gateway: 10.6.0.1

